# Generated by Django 5.1.5 on 2025-01-27 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_supplier_planitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationitem',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.name'),
        ),
        migrations.AlterField(
            model_name='planitem',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.name'),
        ),
    ]
